# Generated by Django 5.0.4 on 2025-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
