# Generated by Django 5.0.4 on 2025-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
